id := "2"
file := "day" + id
asm_file := file + ".asm"
obj_file := file + ".o"
exec_file := file
input_file := "input" + id + ".txt"

build:
    nasm -f elf64 -g -F dwarf {{asm_file}} && gcc -no-pie {{obj_file}} -o {{exec_file}}

run:
    just build
    ./{{exec_file}} < {{input_file}}

clean:
    rm -f {{obj_file}} {{exec_file}}

debug:
    just build
    gdb ./{{exec_file}}
